# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: robot.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0brobot.proto\x12\x05robot\"\x87\x01\n\nRobotState\x12\x14\n\x0cjoint_angles\x18\x01 \x03(\x01\x12\x18\n\x10joint_velocities\x18\x02 \x03(\x01\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\x12\t\n\x01z\x18\x05 \x01(\x01\x12\x0c\n\x04roll\x18\x06 \x01(\x01\x12\r\n\x05pitch\x18\x07 \x01(\x01\x12\x0b\n\x03yaw\x18\x08 \x01(\x01\"\x8a\x01\n\nSensorData\x12\x11\n\timage_rgb\x18\x01 \x01(\x0c\x12\x13\n\x0bimage_depth\x18\x02 \x01(\x0c\x12\x14\n\x0ctimestamp_ns\x18\x03 \x01(\x03\x12 \n\x05state\x18\x04 \x01(\x0b\x32\x11.robot.RobotState\x12\x1c\n\x14language_instruction\x18\x05 \x01(\t\"\x90\x01\n\tActionCmd\x12\x1b\n\x13target_joint_angles\x18\x01 \x03(\x01\x12\x1f\n\x17target_joint_velocities\x18\x02 \x03(\x01\x12\x17\n\x0fgripper_opening\x18\x03 \x01(\x01\x12\x14\n\x0ctimestamp_ns\x18\x04 \x01(\x03\x12\x16\n\x0einference_time\x18\x05 \x01(\x03\x32J\n\x0eRobotInference\x12\x38\n\x0b\x43ommunicate\x12\x11.robot.SensorData\x1a\x10.robot.ActionCmd\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTSTATE']._serialized_start=23
  _globals['_ROBOTSTATE']._serialized_end=158
  _globals['_SENSORDATA']._serialized_start=161
  _globals['_SENSORDATA']._serialized_end=299
  _globals['_ACTIONCMD']._serialized_start=302
  _globals['_ACTIONCMD']._serialized_end=446
  _globals['_ROBOTINFERENCE']._serialized_start=448
  _globals['_ROBOTINFERENCE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
